#ifndef MULTIFACTORALGLIB_GLOBAL_H
#define MULTIFACTORALGLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTIFACTORALGLIB_LIBRARY)
#  define MULTIFACTORALGLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MULTIFACTORALGLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTIFACTORALGLIB_GLOBAL_H
